import MemoryOperational

#print axioms MemoryOperational.Machine.equivalent_after_step_derivative
#print axioms MemoryOperational.Machine.equivalent_after_step_of_prepend_closed
#print axioms MemoryOperational.Realization.compile_eq_implies_equivalent
#print axioms KernelOperational.State.read_compile_eq_rawRead
#print axioms KernelOperational.State.append_toMatrix
#print axioms KernelOperational.Realization.compiled_eq_implies_all_append_futures_equivalent
#print axioms KernelOperational.restrictedKernelSpan_mono
#print axioms MemoryOperational.Softmax.bounded_language_read_exact
#print axioms MemoryOperational.Softmax.bounded_language_compiled_eq_right_congruence
#print axioms KernelOperational.SoftmaxSeparation.summary_eq_iff_all_positive_weight_append_reads
#print axioms KernelOperational.SoftmaxSeparation.state_eq_iff_fixed_key_all_value_future_reads
#print axioms KernelOperational.linearIndependent_of_evaluation_det_ne_zero
#print axioms KernelOperational.softmaxKernelSpan_finrank_eq_card_of_evaluation_det_ne_zero
#print axioms KernelOperational.softmaxKernelSpan_finrank_eq_card_of_injective_queries
#print axioms KernelOperational.SoftmaxReachable.summaryJacobian_injective
#print axioms KernelOperational.SoftmaxReachable.summaryJacobian_finrank_range
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasFDerivAt_summaryJacobian
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasStrictFDerivAt
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_map_nhds_eq
#print axioms KernelOperational.SoftmaxReachable.softmaxLineCacheSummary_eq_richSummaryMap_fin
#print axioms KernelOperational.SoftmaxReachable.exists_softmaxLineCacheSummary_map_nhds_eq
#print axioms KernelOperational.SoftmaxReachable.affine_exact_summary_realization_lower_bound
#print axioms KernelOperational.SoftmaxReachable.continuous_state_dimension_lower_bound_of_open_obstruction
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.local_injOn
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.dimension_lower_bound_of_open_obstruction
#print axioms KernelOperational.SoftmaxReachable.exists_direction_continuous_exact_softmax_probe_dimension_lower_bound
