import MemoryOperational.KernelRealization
import Mathlib.Data.Fintype.Card

namespace MemoryOperational

/-- All forced token continuations of length at most H, represented by their
length and a token assignment at that length. -/
abbrev BoundedContinuation (Token : Type*) (H : ℕ) :=
  Sigma (fun h : Fin (H + 1) => Fin h.val → Token)

instance boundedContinuationFintype
    {Token : Type*} [Fintype Token] (H : ℕ) :
    Fintype (BoundedContinuation Token H) := inferInstance

/-- Exact size of the complete bounded continuation language. -/
theorem card_boundedContinuation
    {Token : Type*} [Fintype Token] (H : ℕ) :
    Fintype.card (BoundedContinuation Token H)
      = ∑ h : Fin (H + 1), Fintype.card Token ^ h.val := by
  rw [Fintype.card_sigma]
  apply Finset.sum_congr rfl
  intro h hh
  rw [Fintype.card_fun, Fintype.card_fin]

namespace Softmax

open KernelOperational

/-- Every deterministic query generator on the complete bounded continuation
language induces an exact finite softmax factorization. -/
noncomputable def boundedFactorization
    {Token κ : Type*} [Fintype Token] [DecidableEq Token] [Fintype κ]
    (H : ℕ) (scale : ℝ)
    (query : BoundedContinuation Token H → κ → ℝ) :
    Factorization (BoundedContinuation Token H) (κ → ℝ)
      (BoundedContinuation Token H) :=
  softmaxFiniteFactorization scale query

/-- Exact one-head finite-horizon recurrentization: compile the current raw KV
cache against every query generated by every forced continuation of length at
most H. Then every such softmax read is reproduced exactly. -/
theorem bounded_language_read_exact
    {Token κ ν : Type*}
    [Fintype Token] [DecidableEq Token] [Fintype κ]
    (H : ℕ) (scale : ℝ)
    (query : BoundedContinuation Token H → κ → ℝ)
    (future : BoundedContinuation Token H)
    (items : List ((κ → ℝ) × (ν → ℝ))) :
    let F := boundedFactorization H scale query
    KernelOperational.State.read F
        (KernelOperational.State.compile F items) future
      = KernelOperational.State.rawRead F future items := by
  dsimp [boundedFactorization]
  exact KernelOperational.State.read_compile_eq_rawRead
    (softmaxFiniteFactorization scale query) future items

/-- The explicit complete bounded-language state dimension is finite and
independent of current raw cache length. This is an upper bound before
quotienting duplicate/dependent reachable queries. -/
theorem bounded_language_state_finrank
    {Token κ ν : Type*}
    [Fintype Token] [DecidableEq Token] [Fintype κ] [Fintype ν]
    (H : ℕ) (scale : ℝ)
    (query : BoundedContinuation Token H → κ → ℝ) :
    let F := boundedFactorization H scale query
    Module.finrank ℝ (KernelOperational.State F ν)
      = (∑ h : Fin (H + 1), Fintype.card Token ^ h.val)
          * (1 + Fintype.card ν) := by
  dsimp [boundedFactorization]
  rw [KernelOperational.state_finrank]
  rw [card_boundedContinuation]

/-- Equality of the complete bounded-language compiled states remains exact
under arbitrary matched future KV appends. Thus the finite-horizon compiler is
a true right congruence for its frozen reachable-query family, not just a
current-read summary. -/
theorem bounded_language_compiled_eq_right_congruence
    {Token κ ν : Type*}
    [Fintype Token] [DecidableEq Token] [Fintype κ]
    (H : ℕ) (scale : ℝ)
    (query : BoundedContinuation Token H → κ → ℝ)
    {xs ys : List ((κ → ℝ) × (ν → ℝ))}
    (h :
      let F := boundedFactorization H scale query
      KernelOperational.State.compile F xs = KernelOperational.State.compile F ys) :
    let F := boundedFactorization H scale query
    (KernelOperational.Realization.rawMachine (ν := ν) F).equivalent
      (fun _ => True) xs ys := by
  dsimp [boundedFactorization] at h ⊢
  exact KernelOperational.Realization.compiled_eq_implies_all_append_futures_equivalent
    (softmaxFiniteFactorization scale query) h

end Softmax
end MemoryOperational
