import MemoryOperational

#print axioms MemoryOperational.Machine.equivalent_after_step_derivative
#print axioms MemoryOperational.Machine.equivalent_after_step_of_prepend_closed
#print axioms MemoryOperational.Machine.equivalent_mono
#print axioms MemoryOperational.Machine.equivalent_horizon_mono
#print axioms MemoryOperational.Machine.equivalent_horizon_after_step
#print axioms MemoryOperational.Machine.equivalent_current_iff
#print axioms MemoryOperational.Realization.compile_run
#print axioms MemoryOperational.Realization.compile_eq_implies_equivalent
#print axioms MemoryOperational.Realization.compile_eq_iff_equivalent

#print axioms KernelOperational.State.denom_append
#print axioms KernelOperational.State.numer_append
#print axioms KernelOperational.State.compile_denom
#print axioms KernelOperational.State.compile_numer
#print axioms KernelOperational.State.read_compile_eq_rawRead
#print axioms KernelOperational.State.append_toMatrix
#print axioms KernelOperational.state_finrank
#print axioms KernelOperational.restrictedKernelSpan_mono
#print axioms KernelOperational.Realization.compiled_eq_implies_all_append_futures_equivalent

#print axioms MemoryOperational.card_boundedContinuation
#print axioms MemoryOperational.Softmax.bounded_language_read_exact
#print axioms MemoryOperational.Softmax.bounded_language_state_finrank
#print axioms MemoryOperational.Softmax.bounded_language_compiled_eq_right_congruence

#print axioms KernelOperational.SoftmaxSeparation.summary_eq_iff_all_positive_weight_append_reads
#print axioms KernelOperational.SoftmaxSeparation.softmax_read_eq_querySummary
#print axioms KernelOperational.SoftmaxSeparation.querySummary_append
#print axioms KernelOperational.SoftmaxSeparation.state_eq_iff_fixed_key_all_value_future_reads

#print axioms KernelOperational.linearIndependent_of_evaluation_det_ne_zero
#print axioms KernelOperational.finrank_restricted_span_eq_card_of_evaluation_det_ne_zero
#print axioms KernelOperational.softmaxKernelSpan_finrank_le_card
#print axioms KernelOperational.softmaxKernelSpan_finrank_eq_card_of_evaluation_det_ne_zero

#print axioms KernelOperational.coeffPolynomial_eq_zero_of_evaluations
#print axioms KernelOperational.powerEvaluationMatrix_det_ne_zero
#print axioms KernelOperational.softmax_evaluation_integer_line_eq_powerMatrix
#print axioms KernelOperational.softmax_integer_line_evaluation_det_ne_zero
#print axioms KernelOperational.softmaxKernelSpan_finrank_eq_card_of_separating_direction
#print axioms KernelOperational.queryDifferencePolynomial_ne_zero
#print axioms KernelOperational.eval_queryDifferencePolynomial
#print axioms KernelOperational.exists_powerDirection_separates_queries
#print axioms KernelOperational.exists_separating_direction_for_softmax
#print axioms KernelOperational.softmaxKernelSpan_finrank_eq_card_of_injective_queries

#print axioms KernelOperational.SoftmaxReachable.expMomentMatrix_eq_powerEvaluation_transpose
#print axioms KernelOperational.SoftmaxReachable.expMomentMatrix_det_ne_zero
#print axioms KernelOperational.SoftmaxReachable.summaryTangent_finrank
#print axioms KernelOperational.SoftmaxReachable.summaryJacobian_injective
#print axioms KernelOperational.SoftmaxReachable.summaryJacobian_finrank_range

#print axioms KernelOperational.SoftmaxPredictiveQuotient.compile_eq_iff_all_append_futures_equivalent_positive_mass
#print axioms KernelOperational.SoftmaxPredictiveQuotient.exactRealization_separating_on_positive_mass

#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasFDerivAt
#print axioms KernelOperational.SoftmaxReachable.richSummaryDerivative_eq_summaryJacobian
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasFDerivAt_summaryJacobian

#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasStrictFDerivAt
#print axioms KernelOperational.SoftmaxReachable.summaryJacobianCLM_injective
#print axioms KernelOperational.SoftmaxReachable.summaryJacobianCLM_surjective
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_hasStrictFDerivAt_equiv
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_map_nhds_eq

#print axioms KernelOperational.SoftmaxReachable.softmaxLineWeight_factor
#print axioms KernelOperational.SoftmaxReachable.softmaxLineCacheSummary_eq_richSummaryMap
#print axioms KernelOperational.SoftmaxReachable.softmaxLineCacheSummary_eq_richSummaryMap_fin

#print axioms MemoryOperational.Machine.run_nil
#print axioms MemoryOperational.Machine.run_cons
#print axioms MemoryOperational.Machine.equivalent_refl
#print axioms MemoryOperational.Machine.equivalent_symm
#print axioms MemoryOperational.Machine.equivalent_trans
#print axioms KernelOperational.State.denom_zero
#print axioms KernelOperational.State.numer_zero
#print axioms KernelOperational.queryDifferencePolynomial_coeff
#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_coeff
#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_ne_zero
#print axioms KernelOperational.SoftmaxReachable.eval_queryProjectionPolynomial
#print axioms KernelOperational.SoftmaxReachable.exists_powerDirection_nonzero_separates_queries
#print axioms KernelOperational.SoftmaxReachable.exists_nonzero_separating_direction_for_softmax
#print axioms KernelOperational.SoftmaxReachable.exists_softmaxLineCacheSummary_map_nhds_eq
#print axioms KernelOperational.SoftmaxReachable.linear_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_exact_summary_realization_lower_bound
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_range_mem_nhds
#print axioms KernelOperational.SoftmaxReachable.exists_nonempty_open_subset_range_richSummaryMap
#print axioms KernelOperational.SoftmaxReachable.continuous_state_dimension_lower_bound_of_open_obstruction
#print axioms KernelOperational.SoftmaxReachable.tangent_eq_iff_all_probe_reads
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_mass_pos
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.summary_eq_of_state_eq
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.local_injOn
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.dimension_lower_bound_of_open_obstruction
#print axioms KernelOperational.SoftmaxReachable.exists_direction_continuous_exact_softmax_probe_dimension_lower_bound
