import MemoryOperational.SoftmaxContinuousSoftmax
import MemoryOperational.SoftmaxGenericLocalOpen
import MemoryOperational.SoftmaxAffineMinimality

#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_coeff
#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_ne_zero
#print axioms KernelOperational.SoftmaxReachable.eval_queryProjectionPolynomial
#print axioms KernelOperational.SoftmaxReachable.exists_powerDirection_nonzero_separates_queries
#print axioms KernelOperational.SoftmaxReachable.exists_nonzero_separating_direction_for_softmax
#print axioms KernelOperational.SoftmaxReachable.exists_softmaxLineCacheSummary_map_nhds_eq

#print axioms KernelOperational.SoftmaxReachable.linear_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_exact_summary_realization_lower_bound
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_range_mem_nhds
#print axioms KernelOperational.SoftmaxReachable.exists_nonempty_open_subset_range_richSummaryMap
#print axioms KernelOperational.SoftmaxReachable.continuous_state_dimension_lower_bound_of_open_obstruction

#print axioms KernelOperational.SoftmaxReachable.tangent_eq_iff_all_probe_reads
#print axioms KernelOperational.SoftmaxReachable.richSummaryMap_mass_pos
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.summary_eq_of_state_eq
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.local_injOn
#print axioms KernelOperational.SoftmaxReachable.ContinuousExactPhysicalProbeRealization.dimension_lower_bound_of_open_obstruction

#print axioms KernelOperational.SoftmaxReachable.exists_direction_continuous_exact_softmax_probe_dimension_lower_bound

