import MemoryOperational.SoftmaxGenericLocalOpen
import MemoryOperational.SoftmaxAffineMinimality

#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_coeff
#print axioms KernelOperational.SoftmaxReachable.queryProjectionPolynomial_ne_zero
#print axioms KernelOperational.SoftmaxReachable.eval_queryProjectionPolynomial
#print axioms KernelOperational.SoftmaxReachable.exists_powerDirection_nonzero_separates_queries
#print axioms KernelOperational.SoftmaxReachable.exists_nonzero_separating_direction_for_softmax
#print axioms KernelOperational.SoftmaxReachable.exists_softmaxLineCacheSummary_map_nhds_eq

#print axioms KernelOperational.SoftmaxReachable.linear_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_state_dimension_lower_bound
#print axioms KernelOperational.SoftmaxReachable.affine_exact_summary_realization_lower_bound
