import MemoryOperational.SoftmaxPhysicalSummary

open BigOperators

namespace KernelOperational
namespace SoftmaxReachable

/-- One physical cache key obtained by moving a base key along a declared
key-space direction by scalar coordinate tau. -/
def lineCacheKey
    {d : Type*} (k0 u : d → ℝ) (tau : ℝ) : d → ℝ :=
  fun a => k0 a + tau * u a

/-- Fixed exponential factor contributed by the base key for one query. -/
noncomputable def lineBaseFactor
    {m d : Type*} [Fintype d]
    (scale : ℝ) (Q : m → d → ℝ) (k0 : d → ℝ) (j : m) : ℝ :=
  Real.exp (scale * ∑ a, Q j a * k0 a)

/-- Query slope along the chosen physical key direction. -/
def lineSlope
    {m d : Type*} [Fintype d]
    (scale : ℝ) (Q : m → d → ℝ) (u : d → ℝ) (j : m) : ℝ :=
  scale * ∑ a, Q j a * u a

/-- The ordinary softmax exponential weight on a key-line cache item factors
into a fixed base-key factor and a scalar exponential in the line coordinate. -/
theorem softmaxLineWeight_factor
    {m d : Type*} [Fintype d]
    (scale : ℝ) (Q : m → d → ℝ) (k0 u : d → ℝ)
    (j : m) (tau : ℝ) :
    Real.exp (scale * ∑ a, Q j a * lineCacheKey k0 u tau a)
      =
    lineBaseFactor scale Q k0 j *
      Real.exp (lineSlope scale Q u j * tau) := by
  unfold lineBaseFactor lineSlope
  rw [← Real.exp_add]
  congr 1
  unfold lineCacheKey
  simp_rw [mul_add]
  rw [Finset.sum_add_distrib]
  calc
    scale *
        ((∑ a, Q j a * k0 a) +
          ∑ a, Q j a * (tau * u a))
        =
      scale *
        ((∑ a, Q j a * k0 a) +
          tau * ∑ a, Q j a * u a) := by
            congr 2
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro a ha
            ring
    _ =
      scale * ∑ a, Q j a * k0 a +
        (scale * ∑ a, Q j a * u a) * tau := by
          ring

/-- Direct physical cache-to-summary map for m independently controlled items
whose keys move along one line. This is the ordinary unnormalized softmax
(Z,M) summary before normalization. -/
noncomputable def softmaxLineCacheSummary
    {m d ν : Type*} [Fintype m] [Fintype d]
    (scale : ℝ) (Q : m → d → ℝ) (k0 u : d → ℝ)
    (x : (m → ℝ) × (ν → m → ℝ)) :
    (m → ℝ) × (ν → m → ℝ) :=
  (fun j =>
      ∑ t : m,
        Real.exp (scale * ∑ a,
          Q j a * lineCacheKey k0 u (x.1 t) a),
   fun b j =>
      ∑ t : m,
        Real.exp (scale * ∑ a,
          Q j a * lineCacheKey k0 u (x.1 t) a) * x.2 b t)

/-- The abstract richSummaryMap used in the derivative proof is exactly the
ordinary softmax physical line-cache summary after substituting the base
factors and query slopes induced by Q, k0, and u. -/
theorem softmaxLineCacheSummary_eq_richSummaryMap
    {m d ν : Type*} [Fintype m] [Fintype d]
    (scale : ℝ) (Q : m → d → ℝ) (k0 u : d → ℝ)
    (x : (m → ℝ) × (ν → m → ℝ)) :
    softmaxLineCacheSummary scale Q k0 u x
      =
    (fun z =>
      (fun j =>
          lineBaseFactor scale Q k0 j *
            ∑ t : m, Real.exp (lineSlope scale Q u j * z.1 t),
       fun b j =>
          lineBaseFactor scale Q k0 j *
            ∑ t : m,
              Real.exp (lineSlope scale Q u j * z.1 t) * z.2 b t)) x := by
  apply Prod.ext
  · funext j
    simp only [softmaxLineCacheSummary]
    simp_rw [softmaxLineWeight_factor scale Q k0 u]
    rw [Finset.mul_sum]
  · funext b j
    simp only [softmaxLineCacheSummary]
    simp_rw [softmaxLineWeight_factor scale Q k0 u]
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro t ht
    ring

/-- Fin-indexed specialization: the physically defined line-cache summary is
literally richSummaryMap with c and lambda generated by the softmax queries. -/
theorem softmaxLineCacheSummary_eq_richSummaryMap_fin
    {m d : ℕ} {ν : Type*} [Fintype ν]
    (scale : ℝ) (Q : Fin m → Fin d → ℝ)
    (k0 u : Fin d → ℝ)
    (x : SummaryTangent m ν) :
    softmaxLineCacheSummary scale Q k0 u x
      =
    richSummaryMap
      (fun j => lineBaseFactor scale Q k0 j)
      (fun j => lineSlope scale Q u j) x := by
  exact softmaxLineCacheSummary_eq_richSummaryMap scale Q k0 u x

end SoftmaxReachable
end KernelOperational
